name: Java Workspace CI

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: 2,20,45 10,12 25-27 1-12/2 *

env:
  IMAGE_NAME: java-workspace-docker
  TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Set docker tag
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        echo "TAG=$(echo ${{ github.ref }} | cut -c 20-)" >> $GITHUB_ENV
    - name: Test Build only
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Clean cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker tag
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "TAG=$(echo ${{ github.ref }} | cut -c 20-)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}